import os
import django

# Set up Django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "quiz_event.settings")
django.setup()

from quiz.models import MCQQuestion

def populate_questions():
    # List of sample questions
    questions = [
    # Lists
    {
        "question_name": "What is the output of the following code?\nprint([1, 2, 3] + [4, 5])",
        "option1": "[1, 2, 3, 4, 5]",
        "option2": "[5, 7]",
        "option3": "Error",
        "option4": "[1, 2, 3][4, 5]",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which method is used to add an element to the end of a list?",
        "option1": "append()",
        "option2": "add()",
        "option3": "insert()",
        "option4": "push()",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(len([1, 2, 3]))",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "Error",
        "correct_answer": "option3",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which method is used to remove the last element from a list?",
        "option1": "remove()",
        "option2": "pop()",
        "option3": "delete()",
        "option4": "clear()",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint([1, 2, 3][1])",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "Error",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },

    # Tuples
    {
        "question_name": "What is the output of the following code?\nprint((1, 2, 3)[2])",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "Error",
        "correct_answer": "option3",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which of the following is used to create a tuple?",
        "option1": "{}",
        "option2": "[]",
        "option3": "()",
        "option4": "<>",
        "correct_answer": "option3",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(len((1, 2, 3)))",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "Error",
        "correct_answer": "option3",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which of the following is true about tuples?",
        "option1": "Tuples are mutable",
        "option2": "Tuples are immutable",
        "option3": "Tuples can be modified after creation",
        "option4": "Tuples use curly braces",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint((1, 2) + (3, 4))",
        "option1": "(1, 2, 3, 4)",
        "option2": "(4, 6)",
        "option3": "Error",
        "option4": "(1, 2)(3, 4)",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },

    # Dictionaries
    {
        "question_name": "What is the output of the following code?\nprint({'a': 1, 'b': 2}['b'])",
        "option1": "1",
        "option2": "2",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which method is used to get all keys from a dictionary?",
        "option1": "keys()",
        "option2": "values()",
        "option3": "items()",
        "option4": "get()",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(len({'a': 1, 'b': 2}))",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "Error",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which method is used to add a new key-value pair to a dictionary?",
        "option1": "add()",
        "option2": "insert()",
        "option3": "update()",
        "option4": "assign()",
        "correct_answer": "option3",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint({'a': 1}.get('b', 0))",
        "option1": "1",
        "option2": "0",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },

    # Sets
    {
        "question_name": "What is the output of the following code?\nprint({1, 2, 3} | {3, 4, 5})",
        "option1": "{1, 2, 3, 4, 5}",
        "option2": "{3}",
        "option3": "Error",
        "option4": "{1, 2, 3}",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which method is used to add an element to a set?",
        "option1": "add()",
        "option2": "append()",
        "option3": "insert()",
        "option4": "push()",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(len({1, 2, 3}))",
        "option1": "1",
        "option2": "2",
        "option3": "3",
        "option4": "Error",
        "correct_answer": "option3",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which of the following is true about sets?",
        "option1": "Sets allow duplicate elements",
        "option2": "Sets are unordered",
        "option3": "Sets use square brackets",
        "option4": "Sets are mutable and ordered",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint({1, 2, 3} - {2})",
        "option1": "{1, 3}",
        "option2": "{2}",
        "option3": "Error",
        "option4": "{1, 2, 3}",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },

    # Type Conversions
    {
        "question_name": "What is the output of the following code?\nprint(int('10'))",
        "option1": "10",
        "option2": "'10'",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which function is used to convert a number to a string?",
        "option1": "str()",
        "option2": "int()",
        "option3": "float()",
        "option4": "chr()",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(float(5))",
        "option1": "5.0",
        "option2": "5",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(str(10) + '20')",
        "option1": "1020",
        "option2": "30",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(bool(0))",
        "option1": "True",
        "option2": "False",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },

    # Basic Python
    {
        "question_name": "What is the output of the following code?\nprint(5 + 3 * 2)",
        "option1": "16",
        "option2": "11",
        "option3": "13",
        "option4": "10",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which of the following is used to define a function in Python?",
        "option1": "def",
        "option2": "function",
        "option3": "define",
        "option4": "func",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint('Hello' * 2)",
        "option1": "HelloHello",
        "option2": "Hello2",
        "option3": "Error",
        "option4": "Hello Hello",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "Which of the following is used to comment a single line in Python?",
        "option1": "//",
        "option2": "#",
        "option3": "/* */",
        "option4": "--",
        "correct_answer": "option2",
        "category": "programming",
        "duration": 15,
    },
    {
        "question_name": "What is the output of the following code?\nprint(10 > 5)",
        "option1": "True",
        "option2": "False",
        "option3": "Error",
        "option4": "None",
        "correct_answer": "option1",
        "category": "programming",
        "duration": 15,
    },
    ]
    # Insert questions into the database
    for question_data in questions:
        MCQQuestion.objects.create(**question_data)
    print("Questions populated successfully!")

if __name__ == "__main__":
    populate_questions()