# Generated by Django 4.2.11 on 2025-03-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
